### ISSUE TITLE
confusing effect

### ISSUE THREAD

**Issue by phil-ho** [KindredKoalas/frontendcapstone#36]
https://github.com/KindredKoalas/frontendcapstone/blob/38c0513f98fbcde5dfe63f740709351ba6efdfbb/client/src/components/ReviewsAndRatings/ReviewsAndRatings.jsx#L90

This effect won't run unless changes are detected in this array `[totalRecommendedReviews, totalNumReviews, averageRating]`. I suspect `product_id` should be a dependency of this effect.

**Comment by Sergiojh-design** [comment]
Change implemented. Thank you!

**Comment by Sergiojh-design** [comment]
Change implemented. Thank you!
