### ISSUE TITLE
use arrow functions to avoid rebinding "this"

### ISSUE THREAD

**Issue by phil-ho** [KindredKoalas/frontendcapstone#46]
https://github.com/KindredKoalas/frontendcapstone/blob/e8af45a4f01bd08064bca8ba09532f75ae1c78ed/client/src/components/ProductDetails/ProductOverview.jsx#L100-L113

you can avoid having to rename `this` if you use arrow functions because arrow functions don't declare their own version of `this`.

```is
    const { product_id } = this.props;

    axios.get(`/api/products/${product_id}`)
      .then((response) => {
        // handle success
        this.setState({
          product: response.data.id,
          category: response.data.name,
          description: response.data.description,
          slogan: response.data.slogan,
          features: response.data.features
        })
        this.getAllStyles();
      })
``

**Comment by jennngai** [comment]
Thanks, refactored to use arrow functions instead
